apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: istio
spec:
  descriptor:
    links:
      - description: Docs
        # needs to match applicationUrl in kots-app.yaml
        url: https://istio.io/latest/docs/
