apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.16.0"
              message: Istio has been tested with Kubernetes 1.16.0 or later, and supports 1.22.0 or later.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.22.0"
              message: Istio has been tested with your Kubernets version, but only 1.22.0 or later are officially supported.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - containerRuntime:
        outcomes:
          - pass:
              when: "== containerd"
              message: containerd container runtime was found.
          - fail:
              message: Did not find containerd container runtime.
    - distribution:
        outcomes:
          - warn:
              when: "== docker-desktop"
              message: The default memory configuration for Docker Destop may lead to failures running Istio
          - warn:
              when: "== microk8s"
              message: Vendor specific installation instructions for MicroK8s have not been updated since version 1.9
          - warn:
              when: "== minikube"
              message: Additional steps are required to deploy to a Minikube cluster
          - pass:
              when: "== eks"
              message: EKS is a supported distribution.
          - pass:
              when: "== gke"
              message: GKE is a supported distribution.
          - pass:
              when: "== aks"
              message: AKS is a supported distribution.
          # Will be supported in the future
          - pass:
              when: "== kurl"
              message: kURL is a supported distribution.
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution.
          - warn:
              message: Unable to determine the distribution of Kubernetes.
    - nodeResources:
        checkName: Memory for desktop Docker Destop
        when: "distribution == docker-desktop"
        outcomes:
          - fail:
              when: "min(memoryCapacity) < 8Gi"
              message: Docker Desktop clusters must have at least 8Gi of memorry
          - pass:
              message: There is at least 8Gi memory avalable
